### ISSUE TITLE
[Create Trade] Buy offers redirect to Your Trades rather than previous page

### ISSUE THREAD

**Issue by trs4ece** [BlackAsLight/DocScripts#7]
After creating a trade, the confirmation screen redirects to the Your Trades page rather than the previous page listing trades. Seeing the previous trades page is helpful to ensure that your trade was posted correctly and differs from the correct behavior seen when posting a sell offer.

**Comment by BlackAsLight** [comment]
This seems to be a bug with what the game thinks your previous page was as it is just redirecting you to that provided url in the back button. I suppose it would look at the url bar and redirect you to that market instead.

**Comment by BlackAsLight** [comment]
Fixed: v2.7 [1e8c81f](https://github.com/BlackAsLight/DocScripts/commit/1e8c81fc340d6c20827cdc0e6c4d52fbac0cfa6e)
